spring:
  config:
    activate:
      on-profile: dev

  datasource:
      url: jdbc:sqlserver://sqlserver:1433;databaseName=video-streaming
#     url: jdbc:sqlserver://localhost:1433;databaseName=video-streaming;encrypt=true;trustServerCertificate=true
    username: sa
    password: Admin@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate:
        format_sql: true

files:
  video: videoDirectory/

aws:
  s3:
    bucket-name: video-streaming-bucket5433
    region: ap-south-1

